# Generated by Django 5.1.3 on 2024-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_aggregator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
